name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install Rust
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Cache dependencies to speed up builds
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Build all milestone projects
      - name: Build
        run: |
          for d in milestone-*; do
            if [ -f "$d/Cargo.toml" ]; then
              echo "Building $d"
              cd $d
              cargo build --verbose
              cd ..
            fi
          done

      # Run tests for all projects
      - name: Test
        run: |
          for d in milestone-*; do
            if [ -f "$d/Cargo.toml" ]; then
              echo "Testing $d"
              cd $d
              cargo test --verbose
              cd ..
            fi
          done